version: '3'

volumes:
  jenkins_home99:

services:
  myjenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home99:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    container_name: myjenkins
